/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Angazovanje;
import model.Izmena;
import model.ModelTabeleAng;
import model.ModelTabeleProf;
import model.Predmet;
import model.Profesor;
import model.Radnik;
import model.Zvanje;
import transfer.KlijentZahtev;
import transfer.ServerOdg;

/**
 *
 * @author USER
 */
public class GlavnaForma extends javax.swing.JDialog {

    /**
     * Creates new form GlavnaForma
     */
//    ucitaj prof i predmete
    private model.ModelTabeleAng ma;
    private model.ModelTabeleProf mp;
    private Radnik r;
    public GlavnaForma(Frame parent, boolean modal, Radnik r) {
        super(parent, modal);
        initComponents();
        this.r=r;
        jLabel.setText("dobrodosli, "+r);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(operacije.Operacije.vrati_profesore, ""));
        ServerOdg so=komunikacija.Komunikacija.getInstance().primiOdg();
        mp=new ModelTabeleProf((List<Profesor>) so.getOdg());
        ma=new ModelTabeleAng(new LinkedList<>());
        jTablea.setModel(ma);
        jTablep.setModel(mp);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(operacije.Operacije.vrati_predmete, ""));
        so=komunikacija.Komunikacija.getInstance().primiOdg();
        for(Predmet p:(List<Predmet>)so.getOdg())
        {
            jComboBox2.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton_dodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablea = new javax.swing.JTable();
        jButton_obrisi = new javax.swing.JButton();
        jButton_sacuvaj = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablep = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_dat = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 77, 136, -1));

        jLabel.setText("jLabel2");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 123, -1));

        jLabel2.setText("ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 71, -1));

        jLabel3.setText("zvanje");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 71, -1));

        jLabel4.setText("prezime");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 71, -1));

        jComboBox1.setModel(new DefaultComboBoxModel<Zvanje>
            (Zvanje.values())
        );
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 108, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 108, -1));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, -1));

        jLabel5.setText("predmet:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 71, -1));

        jButton_dodaj.setText("dodaj predmet");
        jButton_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dodajActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_dodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 127, -1));

        jTablea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 322, 229));

        jButton_obrisi.setText("obrisi angazovanje");
        jButton_obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_obrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_obrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 236, -1, -1));

        jButton_sacuvaj.setText("sacuvaj prof i angazovanja");
        jButton_sacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_sacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 483, -1, -1));

        jTablep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablep);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 259, 405));

        jButton4.setText("prikazi angazovanja");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 142, -1));

        jLabel6.setText("datum");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 71, -1));
        getContentPane().add(jTextField_dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 108, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dodajActionPerformed
       if(ma.getAng().size()==3)return ;
        Date d;
        try {
            d=new SimpleDateFormat("dd.MM.yyyy.").parse(jTextField_dat.getText());
        } catch (Exception e) {d=null;}
        Angazovanje a=new Angazovanje(null, (Predmet) jComboBox2.getSelectedItem(), d, r.getMail());
        if(ma.getAng().contains(a))return ;
        ma.getAng().add(a);
        ma.fireTableDataChanged();
    }//GEN-LAST:event_jButton_dodajActionPerformed

    private void jButton_obrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_obrisiActionPerformed
        if(jTablea.getSelectedRows().length==0)return ;
        int []indexi=jTablea.getSelectedRows();
        List<Angazovanje>ukloni=new LinkedList<>();
        for(int i:indexi)
        {
            ukloni.add(ma.getAng().get(i));
        }
        for(Angazovanje a:ukloni)
        {
            ma.getAng().remove(a);
        }
        ma.fireTableDataChanged();
    }//GEN-LAST:event_jButton_obrisiActionPerformed

    private void jButton_sacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sacuvajActionPerformed
        Profesor p=new Profesor(-1, jTextField1.getText(), jTextField2.getText(), r.getMail(), (Zvanje) jComboBox1.getSelectedItem());
        for(Angazovanje a:ma.getAng())
        {
            a.setP(p);
        }
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(operacije.Operacije.sacuvaj_prof_i_ang, new Izmena(ma.getAng(), p)));
        ServerOdg so=komunikacija.Komunikacija.getInstance().primiOdg();
        if((boolean)so.getOdg())
            JOptionPane.showMessageDialog(this, "uspesno sacuvano");
        else 
            JOptionPane.showMessageDialog(this, "neuspesno sacuvano");
//        osveziti polja
        osvezipolja();
        ucitajNastavnikeOpet();
    }//GEN-LAST:event_jButton_sacuvajActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTablep.getSelectedRow()==-1)return ;
        FormaAng a=new FormaAng(this, rootPaneCheckingEnabled, mp.getProfesori().get(jTablep.getSelectedRow()),r.getMail());
        a.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_dodaj;
    private javax.swing.JButton jButton_obrisi;
    private javax.swing.JButton jButton_sacuvaj;
    private javax.swing.JComboBox<Zvanje> jComboBox1;
    private javax.swing.JComboBox<Predmet> jComboBox2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablea;
    private javax.swing.JTable jTablep;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_dat;
    // End of variables declaration//GEN-END:variables

    private void osvezipolja() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField_dat.setText("");
        ma.getAng().clear();
        ma.fireTableDataChanged();
//        osvezi nastavnike
    }

    private void ucitajNastavnikeOpet() {
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentZahtev(operacije.Operacije.vrati_profesore, ""));
        ServerOdg so=komunikacija.Komunikacija.getInstance().primiOdg();
        mp=new ModelTabeleProf((List<Profesor>) so.getOdg());
        jTablep.setModel(mp);
    }
}
